UAS DATA MINING

- Marta Yulianti / 215314154
- Victoria Alysha F S / 215314158

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Baca File

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
#Baca File
df_1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Dataset_1.csv", sep = ";")
df_1

,ID_Siswa,JK,Sekolah,Skor_Total,Waktu,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15
0,1.0,L,SMP A,61,42 min 43 detik,"6,67","6,67","-1,67","6,67","-1,67","-1,33","6,67","6,67","6,67","6,67","-1,33","6,67","6,67","0,00","6,67"
1,2.0,P,SMP A,21,31 min 30 detik,"6,67","6,67","6,67","-0,83","-1,67","-1,33","-1,67","6,67","-1,67","-1,67","6,67","-1,67","-1,67","0,00","0,00"
2,3.0,P,SMP A,84,44 min 45 detik,"6,67","6,67","6,67","-0,83","6,67","6,67","-1,67","6,67","6,67","6,67","6,67","6,67","6,67","6,67","6,67"
3,4.0,P,SMP A,38,44 min 55 detik,"6,67","-1,67","6,67","-0,83","6,67","-1,33","6,67","6,67","6,67","6,67","-1,33","-1,67","-1,67","0,00","0,00"
4,5.0,P,SMP A,70,43 min 49 detik,"6,67","6,67","6,67","-0,83","6,67","6,67","-1,67","6,67","6,67","6,67","-1,33","6,67","6,67","6,67","0,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,393.0,P,SMP F,13,27 min 38 detik,"-1,67","-1,67","-1,67","-0,83","-1,67","6,67","-1,67","6,67","6,67","6,67","-1,33","-1,67","-1,67","0,00","0,00"
393,394.0,P,SMP F,5,34 min 25 detik,"-1,67","6,67","-1,67","-0,83","6,67","-1,33","-1,67","-1,67","6,67","-1,67","-1,33","-1,67","-1,67","0,00","0,00"
394,395.0,L,SMP F,2,16 min 13 detik,"6,67","-1,67","-1,67","-0,83","-1,67","-1,33","-1,67","-1,67","6,67","-1,67","-1,33",-,"-1,67","0,00","0,00"
395,396.0,P,SMP F,20,15 min,"6,67","-1,67","6,67","-0,83","-1,67","-1,33","-1,67","-1,67","6,67","-1,67","-1,33","6,67","-1,67","0,00","6,67"
396,NaN,L,NaN,12,11 min 47 detik,"6,67","-1,67","-1,67","-0,83","-1,67","-1,33","-1,67","-1,67","-1,67","-1,67","-1,33","-1,67","-1,67","0,00","0,00"

In [9]:
#Baca File
df_2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Dataset_2.csv", sep = ";")
df_2

,ID_Siswa,Sekolah,Jml_ikut,Persiapan,Wkt_persiapan,N_Bindo,N_IPA,N_Mat,Kesan,Minat
0,1,SMP A,3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,> 90,> 90,Menantang,Ya
1,2,SMP A,1 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 5 jam, tapi kurang dari...",> 90,81 - 90,> 90,"Menyenangkan, Menantang",Ya
2,3,SMP A,3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,Lebih dari 7 jam,> 90,> 90,> 90,"Menyenangkan, Menantang, Penting untuk dipelaj...",Ya
3,4,SMP A,> 3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 1 jam, tapi kurang dari...",81 - 90,81 - 90,81 - 90,Biasa saja,Ya
4,5,SMP A,3 kali,Belajar mengerjakan soal Bebras bersama Ibu/Ba...,Kurang dari 1 jam,81 - 90,81 - 90,81 - 90,"Menyenangkan, Biasa saja",Ya
...,...,...,...,...,...,...,...,...,...,...
391,392,SMP F,2 kali,Belajar mengerjakan soal Bebras sendiri di rumah,Kurang dari 1 jam,81 - 90,71 - 80,71 - 80,"Menantang, Sulit dipahami",Ya
392,393,SMP F,2 kali,Belajar mengerjakan soal Bebras bersama Ibu/Ba...,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,71 - 80,71 - 80,"Menyenangkan, Penting untuk dipelajari, Sulit ...",Ya
393,394,SMP F,1 kali,Belajar mengerjakan soal Bebras sendiri di rumah,"Lebih atau sama dengan 1 jam, tapi kurang dari...",71 - 80,71 - 80,71 - 80,"Menantang, Penting untuk dipelajari",Ya
394,395,SMP F,2 kali,Belajar mengerjakan soal Bebras sendiri di rumah,Kurang dari 1 jam,71 - 80,71 - 80,61 - 70,"Menantang, Sulit dipahami",Tidak
395,396,SMP F,2 kali,Belajar mengerjakan soal Bebras sendiri di rumah,"Lebih atau sama dengan 1 jam, tapi kurang dari...",61 - 70,<= 60,<= 60,Sulit dipahami,Ya

# Preprocessing Data

## Join DataFrame

In [10]:
df = pd.merge(df_1, df_2,how='outer', on=['ID_Siswa','Sekolah'])
df

,ID_Siswa,JK,Sekolah,Skor_Total,Waktu,Q1,Q2,Q3,Q4,Q5,...,Q14,Q15,Jml_ikut,Persiapan,Wkt_persiapan,N_Bindo,N_IPA,N_Mat,Kesan,Minat
0,1.0,L,SMP A,61,42 min 43 detik,"6,67","6,67","-1,67","6,67","-1,67",...,"0,00","6,67",3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,> 90,> 90,Menantang,Ya
1,2.0,P,SMP A,21,31 min 30 detik,"6,67","6,67","6,67","-0,83","-1,67",...,"0,00","0,00",1 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 5 jam, tapi kurang dari...",> 90,81 - 90,> 90,"Menyenangkan, Menantang",Ya
2,3.0,P,SMP A,84,44 min 45 detik,"6,67","6,67","6,67","-0,83","6,67",...,"6,67","6,67",3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,Lebih dari 7 jam,> 90,> 90,> 90,"Menyenangkan, Menantang, Penting untuk dipelaj...",Ya
3,4.0,P,SMP A,38,44 min 55 detik,"6,67","-1,67","6,67","-0,83","6,67",...,"0,00","0,00",> 3 kali,Belajar mengerjakan soal Bebras sendiri di rum...,"Lebih atau sama dengan 1 jam, tapi kurang dari...",81 - 90,81 - 90,81 - 90,Biasa saja,Ya
4,5.0,P,SMP A,70,43 min 49 detik,"6,67","6,67","6,67","-0,83","6,67",...,"6,67","0,00",3 kali,Belajar mengerjakan soal Bebras bersama Ibu/Ba...,Kurang dari 1 jam,81 - 90,81 - 90,81 - 90,"Menyenangkan, Biasa saja",Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,393.0,P,SMP F,13,27 min 38 detik,"-1,67","-1,67","-1,67","-0,83","-1,67",...,"0,00","0,00",2 kali,Belajar mengerjakan soal Bebras bersama Ibu/Ba...,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,71 - 80,71 - 80,"Menyenangkan, Penting untuk dipelajari, Sulit ...",Ya
393,394.0,P,SMP F,5,34 min 25 detik,"-1,67","6,67","-1,67","-0,83","6,67",...,"0,00","0,00",1 kali,Belajar mengerjakan soal Bebras sendiri di rumah,"Lebih atau sama dengan 1 jam, tapi kurang dari...",71 - 80,71 - 80,71 - 80,"Menantang, Penting untuk dipelajari",Ya
394,395.0,L,SMP F,2,16 min 13 detik,"6,67","-1,67","-1,67","-0,83","-1,67",...,"0,00","0,00",2 kali,Belajar mengerjakan soal Bebras sendiri di rumah,Kurang dari 1 jam,71 - 80,71 - 80,61 - 70,"Menantang, Sulit dipahami",Tidak
395,396.0,P,SMP F,20,15 min,"6,67","-1,67","6,67","-0,83","-1,67",...,"0,00","6,67",2 kali,Belajar mengerjakan soal Bebras sendiri di rumah,"Lebih atau sama dengan 1 jam, tapi kurang dari...",61 - 70,<= 60,<= 60,Sulit dipahami,Ya
396,NaN,L,NaN,12,11 min 47 detik,"6,67","-1,67","-1,67","-0,83","-1,67",...,"0,00","0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Dataset_Bebras.csv', index=False)

In [12]:
#mencari tahu unique values

for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in ID_Siswa: [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196.
 197. 198. 199. 200. 201. 202. 203. 204. 205. 206. 207. 208. 209. 210.
 211. 212. 213. 214. 215. 216. 217. 218. 219. 220. 221. 222. 223. 224.
 225. 226. 227. 228. 229. 230. 231. 232. 233. 234. 235. 236. 237. 238.
 239. 240. 241. 242. 243. 244. 245. 246. 247. 248. 249. 250. 251. 252.
 253. 254. 255. 256. 257. 258. 259. 260. 261. 262. 263. 264. 265. 266.
 267. 268. 269. 270. 271. 272. 273. 274. 275. 276. 277. 278. 279. 280.
 281. 282. 283. 284. 285. 286. 287. 288. 289. 290. 291. 292. 293. 294.
 295. 296. 297. 298. 299. 300. 301. 302. 303. 304. 305. 306. 307. 308.
 309. 310. 311. 312. 313. 314. 315. 316. 317. 318. 319. 320. 321. 322.
 323. 324. 325. 326. 327. 328. 329. 330. 331. 332. 333. 334. 335. 336.
 337. 338. 339. 340. 341. 342. 343. 344. 345. 346. 347. 348. 349. 350.
 351. 352. 353. 354. 355. 356. 357. 358. 359. 360. 361. 362. 363. 364.
 365. 366. 367. 368. 369. 370. 371. 372. 373. 374. 375. 376. 377. 378.
 379. 380. 381. 382. 383. 384. 385. 386. 387. 388. 389. 390. 391. 392.
 393. 394. 395. 396.  nan]
Unique values in JK: ['L' 'P']
Unique values in Sekolah: ['SMP A' 'SMP B' 'SMP C' 'SMP D' 'SMP E' 'SMP F' nan]
Unique values in Skor_Total: [61 21 84 38 70 83 30  3 22  5  4 28 12 49 13 46  6  2 54  0 20 37 23 11
 17 44 19 29 59 36  8  1 67 27 16  7 43 10 15 52 53 26 45]
Unique values in Waktu: ['42 min 43 detik' '31 min 30 detik' '44 min 45 detik' '44 min 55 detik'
 '43 min 49 detik' '44 min 36 detik' '32 min 26 detik' '41 min 57 detik'
 '43 min 16 detik' '25 min 2 detik' '40 min 54 detik' '33 min 43 detik'
 '40 min 40 detik' '38 min 29 detik' '45 min' '45 min 1 detik'
 '36 min 9 detik' '43 min 35 detik' '30 min 30 detik' '44 min 33 detik'
 '21 min 25 detik' '39 min 53 detik' '31 min 53 detik' '26 min 47 detik'
 '37 min 23 detik' '5 min 54 detik' '38 min 24 detik' '35 min 14 detik'
 '31 min 28 detik' '40 min 41 detik' '11 min 51 detik' '15 min 10 detik'
 '28 min 24 detik' '33 min 3 detik' '35 min 53 detik' '36 min 48 detik'
 '13 min 19 detik' '37 min 26 detik' '42 min 28 detik' '42 min 4 detik'
 '32 min 22 detik' '30 min 46 detik' '25 min 25 detik' '44 min 38 detik'
 '35 min 56 detik' '21 min 14 detik' '15 min 34 detik' '13 min 34 detik'
 '43 min 38 detik' '29 min 18 detik' '38 min 31 detik' '45 min 2 detik'
 '44 min 39 detik' '35 min 31 detik' '42 min 49 detik' '43 min 53 detik'
 '8 min' '22 min 21 detik' '24 min 9 detik' '32 min 32 detik'
 '40 min 30 detik' '39 min 27 detik' '12 min 35 detik' '42 min 59 detik'
 '42 min 50 detik' '6 min 30 detik' '37 min 59 detik' '17 min 54 detik'
 '33 min 34 detik' '41 min 46 detik' '10 min 23 detik' '27 min 59 detik'
 '40 min 16 detik' '7 min 37 detik' '28 min 6 detik' '45 min 3 detik'
 '36 min 51 detik' '27 min 15 detik' '1 min 42 detik' '23 min 52 detik'
 '44 min 19 detik' '40 min 42 detik' '40 min 52 detik' '30 min 5 detik'
 '39 min 58 detik' '37 min 2 detik' '37 min 10 detik' '28 min 47 detik'
 '26 min 26 detik' '41 min 48 detik' '23 min 8 detik' '41 min 28 detik'
 '44 min 54 detik' '32 min 48 detik' '40 min 25 detik' '25 min 8 detik'
 '32 min 57 detik' '23 min 45 detik' '42 min 42 detik' '5 min 4 detik'
 '4 min 3 detik' '39 min 17 detik' '34 min 56 detik' '44 min 59 detik'
 '28 min 39 detik' '44 min 30 detik' '19 min 34 detik' '15 min 44 detik'
 '31 min 33 detik' '38 min 9 detik' '37 min 18 detik' '42 min 1 detik'
 '42 min 3 detik' '29 min 33 detik' '20 min 44 detik' '20 min 46 detik'
 '25 min 52 detik' '2 min 5 detik' '24 min 31 detik' '37 min 11 detik'
 '18 min 54 detik' '35 min 10 detik' '33 min 19 detik' '29 min 21 detik'
 '40 min 7 detik' '32 min 54 detik' '12 min 48 detik' '44 min 14 detik'
 '23 min 18 detik' '37 min 34 detik' '33 min 8 detik' '30 min 29 detik'
 '41 min 22 detik' '37 min 13 detik' '5 min 11 detik' '37 min 40 detik'
 '30 min 10 detik' '35 min 1 detik' '40 min 39 detik' '14 min 52 detik'
 '44 min 52 detik' '43 min 44 detik' '41 min 20 detik' '2 min 57 detik'
 '27 min 24 detik' '24 min 58 detik' '27 min 56 detik' '8 min 30 detik'
 '11 min 28 detik' '39 min 6 detik' '18 min 20 detik' '45 min 23 detik'
 '2 min 47 detik' '25 min 36 detik' '42 min 35 detik' '17 min'
 '44 min 34 detik' '33 min 23 detik' '45 min 12 detik' '45 min 11 detik'
 '33 min 56 detik' '45 min 16 detik' '12 min 15 detik' '18 min 8 detik'
 '32 min 42 detik' '45 min 25 detik' '39 min 54 detik' '39 min 41 detik'
 '44 min 23 detik' '24 min 14 detik' '43 min 42 detik' '34 min 50 detik'
 '15 min 50 detik' '42 min 23 detik' '43 min 17 detik' '35 min 6 detik'
 '35 min 17 detik' '9 min 27 detik' '27 min 10 detik' '12 min 36 detik'
 '26 min 41 detik' '31 min 9 detik' '25 min 41 detik' '30 min 49 detik'
 '44 min 37 detik' '44 min 20 detik' '6 min 42 detik' '24 min 20 detik'
 '45 min 47 detik' '33 min 59 detik' '44 min 50 detik' '31 min 51 detik'
 '34 min 46 detik' '22 min 18 detik' '8 min 26 detik' '39 min 34 detik'
 '14 min 32 detik' '40 min 4 detik' '23 min 25 detik' '10 min 8 detik'
 '34 min 21 detik' '18 min 23 detik' '17 min 25 detik' '21 min 20 detik'
 '38 min 39 detik' '27 min 35 detik' '41 min 12 detik' '25 min 1 detik'
 '31 min 47 detik' '44 min 58 detik' '37 min 38 detik' '21 min 45 detik'
 '25 min 57 detik' '21 min 59 detik' '32 min 13 detik' '31 min 11 detik'
 '43 min 26 detik' '15 min 43 detik' '43 min 47 detik' '19 min 12 detik'
 '27 min 27 detik' '33 min 58 detik' '41 min 29 detik' '25 min 14 detik'
 '36 min 39 detik' '27 min 21 detik' '10 min 36 detik' '26 min 31 detik'
 '25 min 27 detik' '35 min 48 detik' '36 min 3 detik' '17 min 24 detik'
 '45 min 17 detik' '41 min 11 detik' '38 min 7 detik' '16 min 23 detik'
 '30 min 43 detik' '37 min 55 detik' '3 min 10 detik' '14 min 33 detik'
 '5 min 23 detik' '22 min 41 detik' '43 min' '34 min 41 detik'
 '13 min 46 detik' '44 min 56 detik' '17 min 48 detik' '29 min 15 detik'
 '44 min 27 detik' '39 min 57 detik' '42 min 48 detik' '29 min 41 detik'
 '10 min 59 detik' '38 min 30 detik' '35 min' '29 min 37 detik'
 '37 min 57 detik' '42 min 26 detik' '33 min 35 detik' '26 min 29 detik'
 '11 min 57 detik' '33 min 2 detik' '28 min 5 detik' '39 min 25 detik'
 '39 min 44 detik' '45 min 7 detik' '18 min 3 detik' '38 min 21 detik'
 '35 min 38 detik' '2 min 10 detik' '27 min 43 detik' '41 min 4 detik'
 '45 min 35 detik' '43 min 24 detik' '18 min 34 detik' '32 min 29 detik'
 '27 min 38 detik' '34 min 25 detik' '16 min 13 detik' '15 min'
 '11 min 47 detik']
Unique values in Q1: ['6,67' '-1,67' '-']
Unique values in Q2: ['6,67' '-1,67' '-']
Unique values in Q3: ['-1,67' '6,67' '-']
Unique values in Q4: ['6,67' '-0,83' '-']
Unique values in Q5: ['-1,67' '6,67' '-']
Unique values in Q6: ['-1,33' '6,67' '-']
Unique values in Q7: ['6,67' '-1,67' '-']
Unique values in Q8: ['6,67' '-1,67' '-']
Unique values in Q9: ['6,67' '-1,67' '-']
Unique values in Q10: ['6,67' '-1,67' '-']
Unique values in Q11: ['-1,33' '6,67' '-']
Unique values in Q12: ['6,67' '-1,67' '-']
Unique values in Q13: ['6,67' '-1,67' '-']
Unique values in Q14: ['0,00' '6,67' '-']
Unique values in Q15: ['6,67' '0,00' '-']
Unique values in Jml_ikut: ['3 kali' '1 kali' '> 3 kali' '2 kali' nan]
Unique values in Persiapan: ['Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama orang tua di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar mengerjakan soal Bebras bersama orang tua di rumah'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge'
 'Belajar mengerjakan soal Bebras sendiri di rumah'
 'Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama orang tua di rumah'
 'Belajar mengerjakan soal Bebras bersama orang tua di rumah'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar mengerjakan soal Bebras bersama orang tua di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar mengerjakan soal Bebras bersama orang tua di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama orang tua di rumah'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar mengerjakan soal Bebras sendiri di rumah'
 'Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah, Belajar mengerjakan soal Bebras bersama orang tua di rumah'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar mengerjakan soal Bebras sendiri di rumah, Belajar mengerjakan soal Bebras bersama Ibu/Bapak Guru di sekolah'
 'Belajar mengerjakan soal Bebras bersama orang tua di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 'Tidak melakukan persiapan khusus untuk mengikuti Bebras Challenge, Belajar mengerjakan soal Bebras sendiri di rumah, Belajar materi lain selain soal Bebras (misal matematika, sains, dsb.)'
 nan]
Unique values in Wkt_persiapan: ['Lebih atau sama dengan 3 jam, tapi kurang dari 5 jam'
 'Lebih atau sama dengan 5 jam, tapi kurang dari 7 jam' 'Lebih dari 7 jam'
 'Lebih atau sama dengan 1 jam, tapi kurang dari 3 jam'
 'Kurang dari 1 jam' 'Tidak ada persiapan sama sekali' nan]
Unique values in N_Bindo: ['> 90' '81 - 90' '71 - 80' '61 - 70' '<= 60' nan]
Unique values in N_IPA: ['> 90' '81 - 90' '71 - 80' '61 - 70' '<= 60' nan]
Unique values in N_Mat: ['> 90' '81 - 90' '71 - 80' '61 - 70' '<= 60' nan]
Unique values in Kesan: ['Menantang' 'Menyenangkan, Menantang'
 'Menyenangkan, Menantang, Penting untuk dipelajari, Sulit dipahami'
 'Biasa saja' 'Menyenangkan, Biasa saja' 'Menantang, Sulit dipahami'
 'Menantang, Penting untuk dipelajari' 'Penting untuk dipelajari'
 'Menyenangkan, Menantang, Penting untuk dipelajari' 'Menyenangkan'
 'Menyenangkan, Penting untuk dipelajari'
 'Menyenangkan, Menantang, Sulit dipahami, Biasa saja'
 'Menyenangkan, Sulit dipahami' 'Penting untuk dipelajari, Biasa saja'
 'Menantang, Penting untuk dipelajari, Sulit dipahami, Biasa saja'
 'Menyenangkan, Menantang, Sulit dipahami' 'Sulit dipahami, Biasa saja'
 'Menantang, Sulit dipahami, Biasa saja'
 'Menyenangkan, Penting untuk dipelajari, Biasa saja'
 'Menantang, Penting untuk dipelajari, Sulit dipahami'
 'Menantang, Biasa saja' 'Gak tahu karena aku tidak pernah ikut'
 'Menyenangkan, Menantang, Penting untuk dipelajari, Sulit dipahami, Biasa saja'
 'Sulit dipahami' 'Penting untuk dipelajari, Sulit dipahami, Biasa saja'
 'Menantang, Penting untuk dipelajari, Biasa saja'
 'Menyenangkan, Menantang, Penting untuk dipelajari, Biasa saja'
 'Nggak tau karena gak pernah ikut' 'Sulit dipahami, susah'
 'Menyenangkan, Menantang, Sulit dipahami, Panik' 'Menantang, '
 'Menyenangkan, Menantang, Biasa saja'
 'Penting untuk dipelajari, Sulit dipahami'
 'Menantang, Ribkha Hafizh Satriani '
 'Menyenangkan, Penting untuk dipelajari, Sulit dipahami' nan]
Unique values in Minat: ['Ya' 'Tidak' nan]

In [13]:
# Untuk mengetahui jenis data
# Categorical columns
cat_col = [col for col in df.columns if df[col].dtype == 'object']
print('Categorical columns :',cat_col)

# Numerical columns
num_col = [col for col in df.columns if df[col].dtype != 'object']
print('Numerical columns :',num_col)

Categorical columns : ['JK', 'Sekolah', 'Waktu', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Jml_ikut', 'Persiapan', 'Wkt_persiapan', 'N_Bindo', 'N_IPA', 'N_Mat', 'Kesan', 'Minat']
Numerical columns : ['ID_Siswa', 'Skor_Total']

## Cek Missing Value

In [14]:
#menghitung jumlah missing values

df.isnull().sum()

ID_Siswa         1
JK               0
Sekolah          1
Skor_Total       0
Waktu            0
Q1               0
Q2               0
Q3               0
Q4               0
Q5               0
Q6               0
Q7               0
Q8               0
Q9               0
Q10              0
Q11              0
Q12              0
Q13              0
Q14              0
Q15              0
Jml_ikut         1
Persiapan        1
Wkt_persiapan    1
N_Bindo          1
N_IPA            1
N_Mat            1
Kesan            1
Minat            1
dtype: int64

## Drop Kolom

In [15]:
#Feature Selection
#Drop baris yang ada NaN
df = df.dropna()

#Drop kolom yag tidak diperlukan
df = df.drop('Persiapan',axis=1)
df = df.drop('Kesan',axis=1)
df = df.drop('ID_Siswa',axis=1)

In [16]:
df

,JK,Sekolah,Skor_Total,Waktu,Q1,Q2,Q3,Q4,Q5,Q6,...,Q12,Q13,Q14,Q15,Jml_ikut,Wkt_persiapan,N_Bindo,N_IPA,N_Mat,Minat
0,L,SMP A,61,42 min 43 detik,"6,67","6,67","-1,67","6,67","-1,67","-1,33",...,"6,67","6,67","0,00","6,67",3 kali,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,> 90,> 90,Ya
1,P,SMP A,21,31 min 30 detik,"6,67","6,67","6,67","-0,83","-1,67","-1,33",...,"-1,67","-1,67","0,00","0,00",1 kali,"Lebih atau sama dengan 5 jam, tapi kurang dari...",> 90,81 - 90,> 90,Ya
2,P,SMP A,84,44 min 45 detik,"6,67","6,67","6,67","-0,83","6,67","6,67",...,"6,67","6,67","6,67","6,67",3 kali,Lebih dari 7 jam,> 90,> 90,> 90,Ya
3,P,SMP A,38,44 min 55 detik,"6,67","-1,67","6,67","-0,83","6,67","-1,33",...,"-1,67","-1,67","0,00","0,00",> 3 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",81 - 90,81 - 90,81 - 90,Ya
4,P,SMP A,70,43 min 49 detik,"6,67","6,67","6,67","-0,83","6,67","6,67",...,"6,67","6,67","6,67","0,00",3 kali,Kurang dari 1 jam,81 - 90,81 - 90,81 - 90,Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,P,SMP F,12,32 min 29 detik,"-1,67","-1,67","-1,67","-0,83","6,67","-1,33",...,"-1,67","-1,67","0,00","0,00",2 kali,Kurang dari 1 jam,81 - 90,71 - 80,71 - 80,Ya
392,P,SMP F,13,27 min 38 detik,"-1,67","-1,67","-1,67","-0,83","-1,67","6,67",...,"-1,67","-1,67","0,00","0,00",2 kali,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,71 - 80,71 - 80,Ya
393,P,SMP F,5,34 min 25 detik,"-1,67","6,67","-1,67","-0,83","6,67","-1,33",...,"-1,67","-1,67","0,00","0,00",1 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",71 - 80,71 - 80,71 - 80,Ya
394,L,SMP F,2,16 min 13 detik,"6,67","-1,67","-1,67","-0,83","-1,67","-1,33",...,-,"-1,67","0,00","0,00",2 kali,Kurang dari 1 jam,71 - 80,71 - 80,61 - 70,Tidak
395,P,SMP F,20,15 min,"6,67","-1,67","6,67","-0,83","-1,67","-1,33",...,"6,67","-1,67","0,00","6,67",2 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",61 - 70,<= 60,<= 60,Ya

## Format waktu ke detik

In [17]:
# Merubah format data Waktu menjadi jumlah detik

import re
from datetime import timedelta

# Function to convert "X min Y sec" to timedelta
def parse_time_string(Waktu):
    match = re.match(r'(\d+)\s*min(?:\s*(\d+)\s*detik)?', Waktu)
    if match:
        menit = int(match.group(1))
        detik = int(match.group(2)) if match.group(2) else 0
        return timedelta(minutes=menit, seconds=detik)
    return pd.NaT  # Return NaT if the format is incorrect

# Optionally, extract time if needed in a specific format (e.g., total seconds or total minutes)
df['Waktu'] = (df['Waktu'].apply(parse_time_string)).dt.total_seconds()

In [18]:
df.head()

,JK,Sekolah,Skor_Total,Waktu,Q1,Q2,Q3,Q4,Q5,Q6,...,Q12,Q13,Q14,Q15,Jml_ikut,Wkt_persiapan,N_Bindo,N_IPA,N_Mat,Minat
0,L,SMP A,61,2563.0,"6,67","6,67","-1,67","6,67","-1,67","-1,33",...,"6,67","6,67","0,00","6,67",3 kali,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,> 90,> 90,Ya
1,P,SMP A,21,1890.0,"6,67","6,67","6,67","-0,83","-1,67","-1,33",...,"-1,67","-1,67","0,00","0,00",1 kali,"Lebih atau sama dengan 5 jam, tapi kurang dari...",> 90,81 - 90,> 90,Ya
2,P,SMP A,84,2685.0,"6,67","6,67","6,67","-0,83","6,67","6,67",...,"6,67","6,67","6,67","6,67",3 kali,Lebih dari 7 jam,> 90,> 90,> 90,Ya
3,P,SMP A,38,2695.0,"6,67","-1,67","6,67","-0,83","6,67","-1,33",...,"-1,67","-1,67","0,00","0,00",> 3 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",81 - 90,81 - 90,81 - 90,Ya
4,P,SMP A,70,2629.0,"6,67","6,67","6,67","-0,83","6,67","6,67",...,"6,67","6,67","6,67","0,00",3 kali,Kurang dari 1 jam,81 - 90,81 - 90,81 - 90,Ya

## Transform Kolom Q

In [19]:
#Bentuk data diubah menjadi float

columns_to_check = ["Q1","Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "Q9", "Q10", "Q11", "Q12","Q13","Q14","Q15"]

for column in columns_to_check:
    df[column] = df[column].replace("-", 0)
    df[column] = df[column].str.replace(',', '.')
    df[column] = df[column].astype(float)
    df[column].fillna(0, inplace = True)

<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)
<ipython-input-19-552bf519ed4a>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(0, inplace = True)

In [20]:
df

,JK,Sekolah,Skor_Total,Waktu,Q1,Q2,Q3,Q4,Q5,Q6,...,Q12,Q13,Q14,Q15,Jml_ikut,Wkt_persiapan,N_Bindo,N_IPA,N_Mat,Minat
0,L,SMP A,61,2563.0,6.67,6.67,-1.67,6.67,-1.67,-1.33,...,6.67,6.67,0.00,6.67,3 kali,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,> 90,> 90,Ya
1,P,SMP A,21,1890.0,6.67,6.67,6.67,-0.83,-1.67,-1.33,...,-1.67,-1.67,0.00,0.00,1 kali,"Lebih atau sama dengan 5 jam, tapi kurang dari...",> 90,81 - 90,> 90,Ya
2,P,SMP A,84,2685.0,6.67,6.67,6.67,-0.83,6.67,6.67,...,6.67,6.67,6.67,6.67,3 kali,Lebih dari 7 jam,> 90,> 90,> 90,Ya
3,P,SMP A,38,2695.0,6.67,-1.67,6.67,-0.83,6.67,-1.33,...,-1.67,-1.67,0.00,0.00,> 3 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",81 - 90,81 - 90,81 - 90,Ya
4,P,SMP A,70,2629.0,6.67,6.67,6.67,-0.83,6.67,6.67,...,6.67,6.67,6.67,0.00,3 kali,Kurang dari 1 jam,81 - 90,81 - 90,81 - 90,Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,P,SMP F,12,1949.0,-1.67,-1.67,-1.67,-0.83,6.67,-1.33,...,-1.67,-1.67,0.00,0.00,2 kali,Kurang dari 1 jam,81 - 90,71 - 80,71 - 80,Ya
392,P,SMP F,13,1658.0,-1.67,-1.67,-1.67,-0.83,-1.67,6.67,...,-1.67,-1.67,0.00,0.00,2 kali,"Lebih atau sama dengan 3 jam, tapi kurang dari...",> 90,71 - 80,71 - 80,Ya
393,P,SMP F,5,2065.0,-1.67,6.67,-1.67,-0.83,6.67,-1.33,...,-1.67,-1.67,0.00,0.00,1 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",71 - 80,71 - 80,71 - 80,Ya
394,L,SMP F,2,973.0,6.67,-1.67,-1.67,-0.83,-1.67,-1.33,...,0.00,-1.67,0.00,0.00,2 kali,Kurang dari 1 jam,71 - 80,71 - 80,61 - 70,Tidak
395,P,SMP F,20,900.0,6.67,-1.67,6.67,-0.83,-1.67,-1.33,...,6.67,-1.67,0.00,6.67,2 kali,"Lebih atau sama dengan 1 jam, tapi kurang dari...",61 - 70,<= 60,<= 60,Ya

## Encode Categorical menjadi Numerical

In [21]:
 # Categorical columns
cat_col = [col for col in df.columns if df[col].dtype == 'object']
print('Categorical columns :',cat_col)

# Numerical columns
num_col = [col for col in df.columns if df[col].dtype != 'object']
print('Numerical columns :',num_col)

Categorical columns : ['JK', 'Sekolah', 'Jml_ikut', 'Wkt_persiapan', 'N_Bindo', 'N_IPA', 'N_Mat', 'Minat']
Numerical columns : ['Skor_Total', 'Waktu', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15']

In [22]:
#melakukan transformasi data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['JK']=le.fit_transform(df['JK'])
df['Sekolah']=le.fit_transform(df['Sekolah'])
df['Jml_ikut']=le.fit_transform(df['Jml_ikut'])
df['Wkt_persiapan']=le.fit_transform(df['Wkt_persiapan'])
df['N_Bindo']=le.fit_transform(df['N_Bindo'])
df['N_IPA']=le.fit_transform(df['N_IPA'])
df['N_Mat']=le.fit_transform(df['N_Mat'])
df['Minat']=le.fit_transform(df['Minat'])

In [23]:
print(df.head())

   JK  Sekolah  Skor_Total   Waktu    Q1    Q2    Q3    Q4    Q5    Q6  ...  \
0   0        0          61  2563.0  6.67  6.67 -1.67  6.67 -1.67 -1.33  ...
1   1        0          21  1890.0  6.67  6.67  6.67 -0.83 -1.67 -1.33  ...
2   1        0          84  2685.0  6.67  6.67  6.67 -0.83  6.67  6.67  ...
3   1        0          38  2695.0  6.67 -1.67  6.67 -0.83  6.67 -1.33  ...
4   1        0          70  2629.0  6.67  6.67  6.67 -0.83  6.67  6.67  ...

    Q12   Q13   Q14   Q15  Jml_ikut  Wkt_persiapan  N_Bindo  N_IPA  N_Mat  \
0  6.67  6.67  0.00  6.67         2              2        4      4      4
1 -1.67 -1.67  0.00  0.00         0              3        4      2      4
2  6.67  6.67  6.67  6.67         2              4        4      4      4
3 -1.67 -1.67  0.00  0.00         3              1        2      2      2
4  6.67  6.67  6.67  0.00         2              0        2      2      2

   Minat
0      1
1      1
2      1
3      1
4      1

[5 rows x 25 columns]

In [24]:
# Categorical columns
cat_col = [col for col in df.columns if df[col].dtype == 'object']
print('Categorical columns :',cat_col)
# Numerical columns
num_col = [col for col in df.columns if df[col].dtype != 'object']
print('Numerical columns :',num_col)

Categorical columns : []
Numerical columns : ['JK', 'Sekolah', 'Skor_Total', 'Waktu', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Jml_ikut', 'Wkt_persiapan', 'N_Bindo', 'N_IPA', 'N_Mat', 'Minat']

#DBSCAN

In [25]:
# DBSCAN
from sklearn.cluster import DBSCAN
from sklearn import metrics

db = DBSCAN(eps=50,min_samples=10).fit(df)
labels = db.labels_
print(labels)
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True

[ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 -1  0  0  0
  1  0 -1  0  0  0  0 -1  0  0 -1  1  0  0  0  0  0 -1  0  0  0  0  0  0
  0  0  1  0  0  0  0 -1  0 -1  0  0 -1  0  1  0  0  0  0  0  0  0  0 -1
 -1  1  0  0  0  0 -1  0  0 -1  0  0 -1  0  0 -1  1  0 -1  1  0  0  1 -1
  1  0  0  0  0  0  0  0  0  0  0  1  1  0  1  0  0  0  0  0  0  0  1  0
  0  1  0 -1 -1  0  0  0  0  1  0  0  0 -1  0 -1  0  0  0  0  0  0  0  0
 -1 -1  1 -1  0  1  0  0 -1  0  0  1  0  0  1 -1  0  0  1  0  0  0  0  0
  0  0  0 -1  0  0  0  0  0  0  0 -1  0  0  0  1  0  0 -1  0  0  0  1  1
  0  1 -1 -1  0  0 -1  0  0  0  0  0  0 -1  1  0  0  0 -1  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1 -1  0
  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 -1  0  0  0  0 -1
  1 -1  1  0  1  0  0  0  0 -1  1  0  0  0  0  0 -1 -1  0 -1  0  0  1 -1
  0  0 -1  0 -1 -1  0  0  0  1  0  1  0  0  0  0  0  0 -1  1 -1  0  0  0
 -1  0 -1  1  0  0  0  1  0  0  0  0  0  1 -1  1  1  0  0  0 -1  0  0  0
 -1  0  0  0  0 -1 -1 -1  0 -1  0  0 -1  0 -1  1  1  0  0  0  0 -1  0  0
  0  0  0  0  0  0  0  0  1  0 -1  0  1  0  0  0  0  0 -1  0  0  0 -1  0
  1  0  0  0  1  0 -1  0  1  0 -1 -1]

In [26]:
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

In [27]:
print ('Estimated number of clus: %d' % n_clusters_)
print('Estimated number of noise points: %d'%n_noise_)
print('Sihouette Coefficient: %0.3f'%metrics.silhouette_score(df, labels))

Estimated number of clus: 2
Estimated number of noise points: 66
Sihouette Coefficient: 0.538

#KMEANS

In [30]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

kmean = KMeans(n_clusters=2, random_state=0, init='k-means++', max_iter=300)
y_kmeans = kmean.fit_predict(df)

# Compute the silhouette score
score = silhouette_score(df, y_kmeans)

# Print the silhouette score
print("Silhouette Score:", score)

Silhouette Score: 0.674273070679227

In [31]:
!pip install kneed

Collecting kneed
  Downloading kneed-0.8.5-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: numpy>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from kneed) (1.26.4)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from kneed) (1.13.1)
Downloading kneed-0.8.5-py3-none-any.whl (10 kB)
Installing collected packages: kneed
Successfully installed kneed-0.8.5

In [32]:
kmeans_kwargs = {
    "init": 'random',
    "n_init": 10,
    "max_iter": 300,
    "random_state": 42
}

sse=[]

for k in range (1,20):
    kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
    kmeans.fit(df)
    sse.append(kmeans.inertia_)

from kneed import KneeLocator
km =KneeLocator(range(1,20),sse,curve="convex", direction = "decreasing")
km.elbow

3